<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/02 11:29:49

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=test_project1',
  'username' => 'krivcovigor',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
