<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2016/09/02 00:26:34
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // sfPropelPlugin_module_libs

  // project

  // project_model

  // application
  'myUser' => 'D:/USR/www/test_project1.localhost/apps/frontend/lib/myUser.class.php',

  // modules

  // propel
  'DBAdapter' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBAdapter.php',
  'DBMSSQL' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBMSSQL.php',
  'DBMySQL' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBMySQL.php',
  'DBNone' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBNone.php',
  'DBOracle' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBOracle.php',
  'DBPostgres' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBPostgres.php',
  'DBSQLite' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/adapter/DBSQLite.php',
  'BasicLogger' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/logger/BasicLogger.php',
  'MojaviLogAdapter' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/logger/MojaviLogAdapter.php',
  'ColumnMap' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/ColumnMap.php',
  'DatabaseMap' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/DatabaseMap.php',
  'MapBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/MapBuilder.php',
  'TableMap' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/TableMap.php',
  'ValidatorMap' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/map/ValidatorMap.php',
  'BaseObject' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/BaseObject.php',
  'NestedSetRecursiveIterator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/NestedSetRecursiveIterator.php',
  'NodeObject' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/NodeObject.php',
  'Persistent' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/Persistent.php',
  'PreOrderNodeIterator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/om/PreOrderNodeIterator.php',
  'Propel' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/Propel.php',
  'PropelException' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/PropelException.php',
  'BasePeer' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/BasePeer.php',
  'Criteria' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'CriterionIterator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'Criterion' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'Join' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/Criteria.php',
  'DebugPDO' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/DebugPDO.php',
  'DebugPDOStatement' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/DebugPDOStatement.php',
  'NodePeer' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/NodePeer.php',
  'PropelColumnTypes' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelColumnTypes.php',
  'PropelDateTime' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelDateTime.php',
  'PropelPager' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelPager.php',
  'PropelPDO' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/util/PropelPDO.php',
  'BasicValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/BasicValidator.php',
  'MatchValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MatchValidator.php',
  'MaxLengthValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MaxLengthValidator.php',
  'MaxValueValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MaxValueValidator.php',
  'MinLengthValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MinLengthValidator.php',
  'MinValueValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/MinValueValidator.php',
  'NotMatchValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/NotMatchValidator.php',
  'RequiredValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/RequiredValidator.php',
  'TypeValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/TypeValidator.php',
  'UniqueValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/UniqueValidator.php',
  'ValidationFailed' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/ValidationFailed.php',
  'ValidValuesValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/vendor/propel/validator/ValidValuesValidator.php',

  // propel_class
  'Propel' => 'D:\\USR\\php\\symfony\\lib\\plugins\\sfPropelPlugin\\lib\\addon\\sfPropelAutoload.php',

  // sfPropelPlugin_lib
  'sfMixer' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfPropel' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfPropelBehavior' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfPropelData' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfPropelDatabaseSchema' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfPropelManyToMany' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfPropelPager' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'SfExtensionObjectBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfExtensionObjectBuilder.php',
  'SfExtensionPeerBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfExtensionPeerBuilder.php',
  'SfMapBuilderBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfMapBuilderBuilder.php',
  'SfMultiExtendObjectBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfMultiExtendObjectBuilder.php',
  'SfNestedSetBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfNestedSetBuilder.php',
  'SfNestedSetPeerBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfNestedSetPeerBuilder.php',
  'SfObjectBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfObjectBuilder.php',
  'SfPeerBuilder' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/builder/SfPeerBuilder.php',
  'sfPropelDatabase' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sfPropelDataRetriever' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDataRetriever.class.php',
  'sfWebDebugPanelPropel' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfFormFilterPropel' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfFormPropel' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfPropelAdminGenerator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelAdminGenerator.class.php',
  'sfPropelCrudGenerator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelCrudGenerator.class.php',
  'sfPropelFormFilterGenerator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfPropelFormGenerator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfPropelGenerator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfPropelLogger' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'sfPropelRoute' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfPropelRouteCollection' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfPhing' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfPhingListener' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfPropelBaseTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfPropelBuildAllLoadTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfPropelBuildAllTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfPropelBuildFiltersTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfPropelBuildFormsTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfPropelBuildModelTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfPropelBuildSchemaTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfPropelBuildSqlTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfPropelDumpDataTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDumpDataTask.class.php',
  'sfPropelGenerateAdminTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfPropelGenerateModuleForRouteTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfPropelGenerateModuleTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfPropelGraphvizTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfPropelInitAdminTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInitAdminTask.class.php',
  'sfPropelInsertSqlTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfPropelLoadDataTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelLoadDataTask.class.php',
  'sfPropelSchemaToXmlTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfPropelSchemaToYmlTask' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfTesterPropel' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfPropelUniqueValidator' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfPropelUniqueValidator.class.php',
  'sfValidatorPropelChoice' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfValidatorPropelChoiceMany' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoiceMany.class.php',
  'sfValidatorPropelUnique' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfWidgetFormPropelChoice' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfWidgetFormPropelChoiceMany' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoiceMany.class.php',
  'sfWidgetFormPropelSelect' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelSelect.class.php',
  'sfWidgetFormPropelSelectMany' => 'D:/USR/php/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelSelectMany.class.php',
);
